/* eslint-disable @next/next/no-before-interactive-script-outside-document */
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import getCurrentUser from './actions/getCurrentUser'
import Script from 'next/script'
import ToastProvider from '@/components/ToastProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className={inter.className}>
          <Navbar currentUser={currentUser} />
          <ToastProvider />
        {children}
        <Script
          src="//dapi.kakao.com/v2/maps/sdk.js?appkey=73a334cfdd1c4e9498d1812ea6445618&libraries=services,clusterer"
          type="text/javascript"
        />
      </body>
    </html>
  )
}
